AllCops:
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 2.3

LineLength:
  Max: 119

MethodLength:
  Max: 20

ClassLength:
  Max: 200

ModuleLength:
  Enabled: false

NumericLiterals:
  Enabled: false

NumericPredicate:
  Enabled: false

Metrics/AbcSize:
  Max: 25
